### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by feross** [node4good/formage#126]
Will there be any new versions to fix outstanding bugs or issues?

**Comment by refack** [comment]
I sure hope not ;)

I'll give everything a look.

**Comment by jontonsoup** [comment]
is there another project that accomplishes the goal of this? It seems to be abandoned.

**Comment by alonronin** [comment]
It's active and in production use.

**Comment by jontonsoup** [comment]
@alonronin I guess its a matter of appearances.... With 46 open issues and no new commits since sept 2014, it seems abandoned. Am I missing a development branch somewhere?

**Comment by jontonsoup** [comment]
Also, http://formage.io is down.

**Comment by alonronin** [comment]
the 2.x branch is active and production ready

**Comment by refack** [comment]
Compatible with mongoose 3.8 and 4
And compatible with node 4 5 6 7 and 8
