### ISSUE TITLE
Why don't you pin your NPM module versions?

### ISSUE THREAD

**Issue by iyobo** [node4good/formage#135]
As it stands, this project is near-impossible to setup and use today given the simple fact that you are not pinning your dependencies. This is actually a terrible thing.

I see a lot of `"<module-name>":<empty string>` lines in your dependencies.
Maybe next time just run `npm install --save <module-name>` instead which automatically adds that module to package.json and also pins the major version for you.

Massaging npm versions manually till something "clicks" defies the entire point of npm and keeps others terribly uninterested in working with your project when they stumble upon it.
It's a shame because this would have been a great project to work on and improve as nothing solid like this exists today that can just wrap around mongoose models complete with geo fields.

Please make a targeted commit modifying package.json with an exact module version configuration that works for the current version of formage and you would have made the first step in making this project active again.

**Comment by refack** [comment]
Took advice.
👍
